### ISSUE TITLE
report an issue links

### ISSUE THREAD

**Issue by JMante1** [SynBioHub/synbiohub.github.io#47]
Currently the Synbiohub issue tracker and api issue tracker links lead to the github repos but not the issue trackers. I think you just need to add /issues on the end. Additionally, can you change the settings so that the links open in a new tab (I think target=blank should be enough in html).

**Comment by PRUBHTEJ** [comment]
Actually, I'm not trying to fiddle with the HTML code, since it might break something. Therefore, I'll try to add a command for this in the config.toml file in the Synbiohub-docs repo.

**Comment by PRUBHTEJ** [comment]
I've corrected the links. Kindly have a look.

**Comment by JMante1** [comment]
The links are better but they still open in the same window.

**Comment by PRUBHTEJ** [comment]
Yes, so that's one thing which I'll be addressing after a few days, since that involves a lot of work. For this we have to add target = blank to every link and there is no unified command in Hugo for that.

**Comment by PRUBHTEJ** [comment]
Addressed this issue. Kindly have a look.

**Comment by JMante1** [comment]
This still doesn't appear to work on my browser. Not sure if it hasn't pushed yet?

**Comment by PRUBHTEJ** [comment]
At this [link](https://wiki.synbiohub.org/questions-and-issues/reportanissue/), you can view the issue trackers. If there is some other addition needed, could you please specify a little bit more? @JMante1

**Comment by PRUBHTEJ** [comment]
> Yes, so that's one thing which I'll be addressing after a few days, since that involves a lot of work. For this we have to add target = blank to every link and there is no unified command in Hugo for that.

And as per opening in the new link, we need to add target=blank, in the HTML every tome we push a new version of the documentation. I'll try to get in touch with the Hugo developers.

**Comment by JMante1** [comment]
Sounds good, let me know what they say. I would think though if you are just using document text you can put in a link in the same way Hugo Academic does. Can you link the md where this is actually written?

**Comment by JMante1** [comment]
Can't you edit line 171 of this file: https://github.com/SynBioHub/synbiohub.github.io/blob/master/questions-and-issues/reportanissue/index.html ? Or does it get overwritten somewhere?

**Comment by PRUBHTEJ** [comment]
This is how it goes. I don't make changes to HTML/CSS/JS files. I make changes to the markdown files. When we do that, then Hugo automatically re-renders it everytime. Hence it does get overwritten, @JMante1.

**Comment by JMante1** [comment]
Can you add a link to the appropriate markdown file?

**Comment by PRUBHTEJ** [comment]
Yes.
That would be possible.
Which is the link, which you want me to add?

**Comment by JMante1** [comment]
Sorry meant this one: https://github.com/SynBioHub/synbiohub-docs/edit/master/content/Questions%20and%20Issues/ReportanIssue.md

**Comment by JMante1** [comment]
Have you tried using this fix: https://stackoverflow.com/questions/32359583/markdown-link-opening-in-new-tab

**Comment by PRUBHTEJ** [comment]
This answer says markdown does not support this. https://stackoverflow.com/a/32359641/13604103
But I'll give it a try.

**Comment by JMante1** [comment]
It is worth trying the one that does say it might work
